# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'authentication' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for authentication
    pod 'Firebase'
    pod 'Firebase/Auth'

  target 'authenticationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
