# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RealtimeDatabase' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealtimeDatabase
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'

  target 'RealtimeDatabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
